/pytorch/aten/src/ATen/native/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/pytorch/aten/src/ATen/native/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
Traceback (most recent call last):
  File "/home/groups3/testgr/EmailClassifier/src/ClassifierSender.py", line 284, in <module>
    with imaplib.IMAP4_SSL('mail.cs.nmsu.edu', 143) as imap:
  File "/usr/lib64/python3.6/imaplib.py", line 1288, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/lib64/python3.6/imaplib.py", line 198, in __init__
    self.open(host, port)
  File "/usr/lib64/python3.6/imaplib.py", line 1301, in open
    IMAP4.open(self, host, port)
  File "/usr/lib64/python3.6/imaplib.py", line 299, in open
    self.sock = self._create_socket()
  File "/usr/lib64/python3.6/imaplib.py", line 1293, in _create_socket
    server_hostname=self.host)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:877)
/pytorch/aten/src/ATen/native/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
Traceback (most recent call last):
  File "/home/groups3/testgr/EmailClassifier/src/ClassifierSender.py", line 284, in <module>
    with imaplib.IMAP4_SSL('mail.cs.nmsu.edu', 110) as imap:
  File "/usr/lib64/python3.6/imaplib.py", line 1288, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/lib64/python3.6/imaplib.py", line 198, in __init__
    self.open(host, port)
  File "/usr/lib64/python3.6/imaplib.py", line 1301, in open
    IMAP4.open(self, host, port)
  File "/usr/lib64/python3.6/imaplib.py", line 299, in open
    self.sock = self._create_socket()
  File "/usr/lib64/python3.6/imaplib.py", line 1293, in _create_socket
    server_hostname=self.host)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:877)
/pytorch/aten/src/ATen/native/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
Traceback (most recent call last):
  File "/home/groups3/testgr/EmailClassifier/src/ClassifierSender.py", line 284, in <module>
    with imaplib.IMAP4_SSL('mail.cs.nmsu.edu', 995) as imap:
  File "/usr/lib64/python3.6/imaplib.py", line 1288, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/lib64/python3.6/imaplib.py", line 201, in __init__
    self._connect()
  File "/usr/lib64/python3.6/imaplib.py", line 249, in _connect
    raise self.error(self.welcome)
imaplib.error: None
/pytorch/aten/src/ATen/native/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
Traceback (most recent call last):
  File "/home/groups3/testgr/EmailClassifier/src/ClassifierSender.py", line 284, in <module>
    with poplib.POP3_SSL('mail.cs.nmsu.edu', '995') as pop:
AttributeError: __enter__
  File "/home/groups3/testgr/EmailClassifier/src/ClassifierSender.py", line 286
    server.logout()
                  ^
TabError: inconsistent use of tabs and spaces in indentation
/pytorch/aten/src/ATen/native/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/pytorch/aten/src/ATen/native/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/pytorch/aten/src/ATen/native/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
Traceback (most recent call last):
  File "/home/groups3/testgr/EmailClassifier/src/ClassifierSender.py", line 284, in <module>
    with imaplib.IMAP4_SSL("cs.nmsu.edu",993) as server:
  File "/usr/lib64/python3.6/imaplib.py", line 1288, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/lib64/python3.6/imaplib.py", line 198, in __init__
    self.open(host, port)
  File "/usr/lib64/python3.6/imaplib.py", line 1301, in open
    IMAP4.open(self, host, port)
  File "/usr/lib64/python3.6/imaplib.py", line 299, in open
    self.sock = self._create_socket()
  File "/usr/lib64/python3.6/imaplib.py", line 1291, in _create_socket
    sock = IMAP4._create_socket(self)
  File "/usr/lib64/python3.6/imaplib.py", line 289, in _create_socket
    return socket.create_connection((host, self.port))
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host
/pytorch/aten/src/ATen/native/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/pytorch/aten/src/ATen/native/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
Traceback (most recent call last):
  File "/home/groups3/testgr/EmailClassifier/src/ClassifierSender.py", line 284, in <module>
    with imaplib.IMAP4_SSL("cs.nmsu.edu",993) as server:
  File "/usr/lib64/python3.6/imaplib.py", line 1288, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/lib64/python3.6/imaplib.py", line 198, in __init__
    self.open(host, port)
  File "/usr/lib64/python3.6/imaplib.py", line 1301, in open
    IMAP4.open(self, host, port)
  File "/usr/lib64/python3.6/imaplib.py", line 299, in open
    self.sock = self._create_socket()
  File "/usr/lib64/python3.6/imaplib.py", line 1291, in _create_socket
    sock = IMAP4._create_socket(self)
  File "/usr/lib64/python3.6/imaplib.py", line 289, in _create_socket
    return socket.create_connection((host, self.port))
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host
/pytorch/aten/src/ATen/native/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
Traceback (most recent call last):
  File "/home/groups3/testgr/EmailClassifier/src/ClassifierSender.py", line 284, in <module>
    with smtplib.SMTP("imap-mail.cs.nmsu.edu", 993) as server:
  File "/usr/lib64/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
